### PR TITLE
Fixed accidental caching of classSearch data

### LINKED ISSUE #4: Banner Proxy returning cached class data instead of new class data.
Making a call to the banner proxy works when you first call and every new call to the banner proxy just returns the results of the first call. Appears is version 3 & 4.

### PR DESCRIPTION
**Pull request by studioph**
Banner Proxy should no longer cache data returned from `classSearch` and instead perform a fresh request each time.

Fixes #4

### CODE REVIEW

**Comment by paulhutchings** [comment]
Closed and reopening since tests action got corrupted.

**Comment by studioph** [comment]
Looks like there is a bug with the GIthub Action for configuring NodeJS: [#132](https://github.com/actions/setup-node/issues/132)

**Review by Jpatel2049 — APPROVED** [review]

**Comment by studioph** [comment]
[Issue 4](https://trello.com/c/2iUbKmYv/25-issue-4)

**Comment by studioph** [comment]
I'm going to need more time to figure out how to properly do this but for now I'm simply going to override and merge so that it gets updated on AWS.

**Pull request merged**
